default_stages: [pre-commit]
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0 # Use the latest stable version
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/psf/black
    rev: 25.11.0 # Use the latest stable version
    hooks:
      - id: black
  - repo: https://github.com/PyCQA/isort
    rev: 7.0.0 # Use the latest stable version
    hooks:
      - id: isort
        name: isort (python)
